AllCops:
  NewCops: enable
require:
  - rubocop-graphql
  - rubocop-rails
  - rubocop-rspec
Style/Documentation:
  Enabled: false
Metrics/MethodLength:
  Exclude: 
    - db/migrate/**/*
RSpec/MultipleMemoizedHelpers:
  Max: 10
GraphQL/ExtractType:
  Enabled: false