default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  host: localhost
  pool: 5
development:
  <<: *default
  database: my-team-church-api_development
test:
  <<: *default
  database: my-team-church-api_test
